#
# /*
#  * Copyright (c) 2025-2026 Jay Shah
#  * SPDX-License-Identifier: Apache-2.0
#  */
#

spring.application.name=letterbox
letterbox.id-generator=62bit
server.port=8080
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/codepaste}
spring.data.mongodb.auto-index-creation=true
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.repositories.enabled=false
